import { colors, radius, sizing, spacing } from "@ckare/design";
import type { PropsWithChildren, ReactNode } from "react";
import { Pressable, StyleSheet, Text, View } from "react-native";

export function Card({ children, accent = false }: PropsWithChildren<{ accent?: boolean }>) { return <View style={[styles.card, accent && styles.cardAccent]}>{children}</View>; }
export function SectionTitle({ children, aside }: PropsWithChildren<{ aside?: ReactNode }>) { return <View style={styles.sectionTitle}><Text accessibilityRole="header" style={styles.sectionLabel}>{children}</Text>{aside}</View>; }
export function PrimaryButton({ label, onPress, disabled = false }: { label: string; onPress: () => void; disabled?: boolean }) { return <Pressable accessibilityRole="button" accessibilityState={{disabled}} disabled={disabled} onPress={onPress} style={[styles.button,disabled&&styles.buttonDisabled]}><Text style={styles.buttonText}>{label}  →</Text></Pressable>; }
export function PolicyBlockers({ blockers }: { blockers: string[] }) { if(blockers.length===0)return null; return <View accessibilityRole="alert" style={styles.blockers}><Text style={styles.blockerTitle}>Action blocked</Text>{blockers.map((blocker)=><Text key={blocker} style={styles.detail}>• {blocker}</Text>)}</View>; }
export function DataRow({ label, value, detail }: { label: string; value: string; detail?: string }) { return <View style={styles.row}><View style={styles.rowCopy}><Text style={styles.rowLabel}>{label}</Text>{detail?<Text style={styles.detail}>{detail}</Text>:null}</View><Text style={styles.rowValue}>{value}</Text></View>; }

export const ui=StyleSheet.create({hero:{backgroundColor:colors.ink,borderRadius:radius.lg,padding:spacing.lg,gap:spacing.md},heroKicker:{color:colors.gold,fontSize:12,fontWeight:"700",letterSpacing:1.2,textTransform:"uppercase"},heroTitle:{color:colors.white,fontFamily:"Georgia",fontSize:28,lineHeight:34},heroBody:{color:colors.mint,fontSize:15,lineHeight:22},grid:{flexDirection:"row",gap:spacing.sm},metric:{flex:1,minHeight:104,backgroundColor:colors.paperRaised,borderRadius:radius.md,padding:spacing.md,borderWidth:1,borderColor:colors.line},metricValue:{color:colors.ink,fontFamily:"Georgia",fontSize:24},metricLabel:{color:colors.inkMuted,fontSize:12,marginTop:spacing.xs},body:{color:colors.inkMuted,fontSize:15,lineHeight:22},title:{color:colors.ink,fontSize:18,fontWeight:"700"},caption:{color:colors.inkMuted,fontSize:12,lineHeight:18},divider:{height:1,backgroundColor:colors.line},amount:{color:colors.ink,fontFamily:"Georgia",fontSize:38},link:{color:colors.mintDeep,fontWeight:"700",fontSize:14},actions:{flexDirection:"row",flexWrap:"wrap",gap:spacing.sm},notice:{color:colors.ink,backgroundColor:colors.mint,borderRadius:radius.sm,padding:spacing.sm,fontSize:13,lineHeight:19},input:{minHeight:sizing.minimumTouchTarget,borderWidth:1,borderColor:colors.line,borderRadius:radius.sm,paddingHorizontal:spacing.sm,color:colors.ink,backgroundColor:colors.white}});
const styles=StyleSheet.create({card:{backgroundColor:colors.paperRaised,borderRadius:radius.md,borderWidth:1,borderColor:colors.line,padding:spacing.md,gap:spacing.sm},cardAccent:{borderLeftColor:colors.mintDeep,borderLeftWidth:4},sectionTitle:{flexDirection:"row",alignItems:"center",justifyContent:"space-between",marginTop:spacing.sm},sectionLabel:{color:colors.ink,fontSize:17,fontWeight:"800"},button:{minHeight:sizing.minimumTouchTarget,backgroundColor:colors.mintDeep,borderRadius:radius.pill,paddingHorizontal:spacing.lg,justifyContent:"center",alignItems:"center",alignSelf:"flex-start"},buttonDisabled:{opacity:.45},buttonText:{color:colors.white,fontWeight:"800",fontSize:14},row:{minHeight:54,flexDirection:"row",justifyContent:"space-between",alignItems:"center",gap:spacing.md,borderBottomWidth:1,borderBottomColor:colors.line,paddingVertical:spacing.sm},rowCopy:{flex:1,gap:2},rowLabel:{color:colors.ink,fontWeight:"700",fontSize:14},rowValue:{color:colors.ink,fontWeight:"700",fontSize:13,textAlign:"right"},detail:{color:colors.inkMuted,fontSize:12},blockers:{backgroundColor:colors.coralSoft,borderRadius:radius.sm,padding:spacing.sm,gap:spacing.xs},blockerTitle:{color:colors.ink,fontWeight:"800",fontSize:13}});
